# Generated by Django 3.1.6 on 2021-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_diaries', '0003_topic_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
