# Generated by Django 3.1.6 on 2021-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_diaries', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
