# Generated by Django 3.1.6 on 2021-02-20 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_diaries', '0005_auto_20210219_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.FileField(blank=True, upload_to='study_diary/media/'),
        ),
    ]
